# -*- coding: utf-8 -*-
"""Boris.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZPn5KJe53ycw6joEEHSCOuMadCb3ldhf
"""


import math
import os
import numpy as np
import tensorflow as tf
from keras.models import load_model
from keras.applications.vgg16 import preprocess_input
from keras.applications.vgg16 import VGG16
from PIL import Image

if not os.path.exists("C:/Users/Jerome's Laptop/Desktop/Boris_KI"):
    print("Download completed. Done!")
else:
    print("Die Dateien existieren bereits")



image = Image.open("C:/Users/Jerome's Laptop/Desktop/Boris_KI/test_particle.jpg")
image.resize((224, 224), Image.LANCZOS)

image = image.resize((224, 224), Image.LANCZOS)
image = np.asarray(image).reshape(1, 224, 224, 3)
image = preprocess_input(image)

#image.shape
vgg16_model = VGG16(include_top=False, input_shape=(224, 224, 3))

X_after_vgg = vgg16_model.predict(image)

X_after_vgg.shape

model = load_model("C:/Users/Jerome's Laptop/Desktop/Boris_KI/particle.h5")
x = model.predict(X_after_vgg)
print(x)

if x >= 0.9: 
  print("is Particle")
else : 
  print("not a Particle")

print(vgg16_model)